CREATE TABLE IF NOT EXISTS PERSONA (
  ID_EMPRESA VARCHAR(4) NOT NULL,
  DNI VARCHAR(8) NOT NULL,
  APE_PATERNO VARCHAR(30),
  APE_MATERNO VARCHAR(30),
  EDAD INTEGER(3),
  PRIMARY KEY (ID_EMPRESA, DNI)
);